ALTER TABLE "Project"
ADD COLUMN "architecture" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "codeDiffs" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "benchmarks" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
