export const CONTENT_MIGRATION_VERSION = "cms-content-v1";

export const profileContent = {
  professionalSummary: "Full-stack software engineer building type-safe web applications, REST APIs, authentication systems, and relational and NoSQL data solutions using React, Next.js, TypeScript, Node.js, Express.js, and Python frameworks. Focused on maintainable architecture, secure integrations, testing, CI/CD, and practical AI-powered application features.",
  availabilityStatus: "Open to full-time roles",
  availabilityText: "Open to opportunities",
  responseTime: "Usually within 24h",
  remoteAvailability: "Remote friendly",
  openToOpportunities: true,
  heroLabel: "Full-stack systems",
  profileReference: "Profile · 001",
  whatsappNumber: "+96176364340",
  whatsappMessage: "Hello Mahmoud, I saw your portfolio.",
  focusAreas: ["React · Next.js · TypeScript", "Node.js · Express.js", "REST APIs", "Authentication · RBAC", "SQL · MongoDB"],
};

export const siteSections = [
  { key: "hero", heading: "Full-Stack Software Engineer", description: "Building secure, scalable, and user-focused web applications.", ctaLabel: "View Projects", ctaUrl: "/projects", order: 0, content: { introduction: "I build production-ready applications using React, Next.js, TypeScript, Node.js, Express.js, and modern database technologies—from REST APIs and authentication to real-time communication and role-based systems.", cvCtaLabel: "Download CV" } },
  { key: "featuredProjects", eyebrow: "Selected work", heading: "Systems built for real workflows", description: "Three full-stack products engineered at the Digital Hub and independently.", ctaLabel: "View all projects", ctaUrl: "/projects", order: 1, content: {} },
  { key: "about", eyebrow: "About", heading: "Building practical web applications, end to end.", order: 2, content: { introduction: "Computer science graduate and full-stack software engineer from Tripoli, Lebanon, interested in junior full-stack and backend roles. I build responsive React and Next.js interfaces backed by secure Node.js, Express.js, NestJS, MongoDB, and SQL data services.", experienceParagraph: "At Ishtari Group, I developed PHP MVC administration modules and SQL reporting workflows. Through The Digital Hub by UNRWA, I collaborated on GameZone Arena, Lobby, and UniHub.", technicalParagraph: "My focus is maintainable API design, authentication, authorization, database validation, and clear team delivery through Git branches, pull requests, and code review. My current project work also uses Python backend frameworks, automated testing, CI/CD, and AI APIs.", statistics: [{ value: "3", label: "Featured team products", visible: true }, { value: "2", label: "Professional roles", visible: true }, { value: "BSc", label: "Computer Science", visible: true }], workflowHeading: "How I work", workMethods: [{ title: "Discovery", description: "Requirement mapping, data modeling, and API contracts agreed before a line of UI is written.", icon: "01", visible: true }, { title: "Build", description: "Typed, tested full-stack code with secure auth, real-time features, and clean APIs.", icon: "02", visible: true }, { title: "Ship", description: "Deployed to production and iterated on feedback from real users and teams.", icon: "03", visible: true }] } },
  { key: "skills", eyebrow: "Stack", heading: "Technical architecture", description: "Technologies used across professional work, completed applications, and current project development.", order: 3, content: {} },
  { key: "technologies", eyebrow: "Stack in use", heading: "Technologies & Tools", description: "Languages, frameworks, databases, and delivery tools used across this portfolio's projects.", order: 4, content: {} },
  { key: "education", eyebrow: "Academic background", heading: "Education", description: "A computer science foundation in software development, databases, and systems.", order: 5, content: {} },
  { key: "certifications", eyebrow: "Credentials", heading: "Training & Courses", description: "Completed learning programs shown separately from professional experience.", order: 6, content: {} },
  { key: "contact", eyebrow: "Contact Mahmoud", heading: "Start a real conversation", description: "Reach out for full-stack roles, contract projects, internships, or collaboration.", order: 7, content: { availabilityOptions: ["Open to full-time roles", "Contract projects", "Technical collaboration"], successHeading: "Message sent", successMessage: "Thanks for reaching out — I usually reply within a couple of days. I'll get back to you at your email.", formHeading: "Send a message", formDescription: "I usually reply within a couple of days.", jobMatchVisible: true, jobMatchHeading: "Try the AI Job Match", jobMatchText: "See how my skills align with a real job description before we even talk.", jobMatchCta: "Match a job" } },
  { key: "footer", description: "Full-stack engineer building React, Next.js and Angular frontends with Node.js and NestJS backends.", order: 8, content: { technologyText: "Built with React 19 · Tailwind CSS v4 · Vite · Deployed on Vercel", copyrightSuffix: "All rights reserved." } },
  { key: "projectsPage", eyebrow: "Portfolio", heading: "Projects", description: "A selection of collaborative and personal full-stack work — from reservation platforms with payments to real-time communication systems.", order: 9, content: { seoTitle: "Projects", seoDescription: "Full-stack projects by Mahmoud Abdul Ghani — reservations with payments, real-time communication, university management, clinic systems and more.", filters: [{ id: "all", label: "All Projects" }, { id: "program", label: "Digital Hub" }, { id: "personal", label: "Personal" }] } },
  { key: "seo", order: 10, content: { titleTemplate: "%s | Mahmoud Hussein Abdul Ghani", siteName: "Mahmoud Abdul Ghani Portfolio", defaultTitle: "Full-Stack Software Engineer", defaultDescription: "Portfolio of Mahmoud Hussein Abdul Ghani, a full-stack software developer building React, Next.js, TypeScript, Node.js, Express.js, MongoDB, and SQL applications.", keywords: ["full-stack developer", "software engineer", "React", "Next.js", "Angular", "Node.js", "Express", "NestJS", "MongoDB", "TypeScript", "portfolio", "Lebanon"], pages: { contact: { title: "Contact", description: "Reach out to Mahmoud Abdul Ghani for junior software engineering roles, full-stack projects, internships, or collaboration." }, cv: { title: "Resume", description: "Professional curriculum vitae." } } } },
  { key: "cvPage", heading: "Resume", description: "Professional curriculum vitae.", order: 11, content: { downloadLabel: "Download PDF", backLabel: "Back to portfolio", unavailableText: "If the preview is unavailable in your browser, use Download PDF." } },
  { key: "jobMatch", heading: "AI Job Match", description: "Compare a job description with the saved portfolio skills, projects, experience, education, and certifications.", order: 12, content: { seoTitle: "Job Match", seoDescription: "Compare a job description with the portfolio owner's verified skills, projects, experience, education, and certifications." } },
  { key: "assistant", heading: "Portfolio AI", description: "Professional portfolio assistant", order: 13, content: { buttonLabel: "Ask Portfolio AI", greeting: "I can help you quickly evaluate the portfolio's projects, skills, experience, and fit for a role.", disclaimer: "Answers are grounded in published portfolio data", prompts: ["Summarize this portfolio for a recruiter.", "What are the strongest projects?", "What technical skills are demonstrated?", "Describe the backend experience.", "Which project best demonstrates full-stack development?", "Where can I download the CV?"] } },
];

export const projectImpactSummaries: Record<string, string> = {
  "gamezone-arena": "Live availability · time-slot conflict detection · Stripe payments",
  lobby: "Persistent identities · temporary guest rooms · real-time voice",
  unihub: "Role-based portals for students, professors and administrators",
};
