import { useState } from "react";
import { FiArrowDown, FiArrowUp, FiCheck, FiPlus, FiTrash2 } from "react-icons/fi";
import { PageMeta } from "../../components/PageMeta";
import { useAdminProfile, useUpdateProfile } from "../../lib/hooks";
import type { ExperienceItem } from "../../types";

const blank = (): ExperienceItem => ({ milestone: "", facility: "", meta: "", details: "", role: "", company: "", description: "", startDate: null, endDate: null, isCurrent: false, location: "" });

export function ExperienceAdmin() {
  const profile = useAdminProfile(); const update = useUpdateProfile();
  const [items, setItems] = useState<ExperienceItem[]>([]); const [loaded, setLoaded] = useState(false);
  if (profile.data && !loaded) { setItems(profile.data.experience); setLoaded(true); }
  const patch = <K extends keyof ExperienceItem>(index: number, key: K, value: ExperienceItem[K]) => setItems((rows) => rows.map((row, i) => i === index ? { ...row, [key]: value } : row));
  const move = (index: number, delta: number) => setItems((rows) => { const next = [...rows]; const target = index + delta; if (target < 0 || target >= next.length) return rows; [next[index], next[target]] = [next[target], next[index]]; return next; });
  const save = () => update.mutate({ experience: items }, { onSuccess: (saved) => setItems(saved.experience) });
  if (profile.isLoading) return <p className="text-sm text-muted">Loading experience…</p>;
  return <div className="mx-auto max-w-4xl space-y-6"><PageMeta title="Manage Experience" /><div><h1 className="admin-heading">Experience</h1><p className="mt-1 text-sm text-muted">Manage the public portfolio timeline. CV-only wording remains in CV Manager.</p></div>
    <div className="space-y-4">{items.map((item, index) => <section key={item.id ?? index} className="card p-5"><div className="mb-4 flex items-center justify-between"><span className="font-mono text-xs text-faint">Order {index + 1}</span><div className="flex gap-1"><button className="btn-icon border border-line" onClick={() => move(index, -1)} disabled={!index} aria-label="Move up"><FiArrowUp /></button><button className="btn-icon border border-line" onClick={() => move(index, 1)} disabled={index === items.length - 1} aria-label="Move down"><FiArrowDown /></button><button className="btn-icon border border-line text-danger" onClick={() => setItems((rows) => rows.filter((_, i) => i !== index))} aria-label="Delete"><FiTrash2 /></button></div></div><div className="grid gap-4 sm:grid-cols-2"><label className="field-label">Role<input className="input mt-1" value={item.role ?? ""} onChange={(e) => patch(index, "role", e.target.value)} /></label><label className="field-label">Company<input className="input mt-1" value={item.company ?? ""} onChange={(e) => patch(index, "company", e.target.value)} /></label><label className="field-label">Start date<input type="month" className="input mt-1" value={item.startDate ?? ""} onChange={(e) => patch(index, "startDate", e.target.value || null)} /></label><label className="field-label">End date<input type="month" className="input mt-1" disabled={item.isCurrent} value={item.endDate ?? ""} onChange={(e) => patch(index, "endDate", e.target.value || null)} /></label><label className="field-label">Location<input className="input mt-1" value={item.location ?? ""} onChange={(e) => patch(index, "location", e.target.value)} /></label><label className="flex items-center gap-2 self-end pb-3 text-sm font-semibold text-ink"><input type="checkbox" checked={item.isCurrent ?? false} onChange={(e) => { patch(index, "isCurrent", e.target.checked); if (e.target.checked) patch(index, "endDate", null); }} />Currently working / Present</label><label className="field-label sm:col-span-2">Description<textarea className="textarea mt-1 min-h-24" value={item.description ?? ""} onChange={(e) => patch(index, "description", e.target.value)} /></label></div></section>)}</div>
    <div className="flex flex-wrap gap-3"><button className="btn-outline" onClick={() => setItems((rows) => [...rows, blank()])}><FiPlus />Add experience</button><button className="btn-primary" onClick={save} disabled={update.isPending}><FiCheck />{update.isPending ? "Saving…" : "Save experience"}</button>{update.isSuccess && <span className="self-center text-sm font-semibold text-ok">Saved</span>}</div>{update.error && <p role="alert" className="text-sm text-danger">{update.error.message}</p>}</div>;
}
